### ISSUE TITLE
Info about .md files

### ISSUE THREAD

**Issue by FroGGog** [FroGGog/gitLearning#6]
Create structured information about .md files, in any form (tables, diagrams, text file) It should be informative. I also suggest adding any interesting data about the design of .md files.

**Comment by ArsenyD** [comment]
There is a Github article that covers the use of markdown in a great detail. https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
